### ISSUE TITLE
release notes and news

### ISSUE THREAD

**Issue by sckott** [ropensci/epubr#1]
hi! looks like you put news items in release notes https://github.com/ropensci/epubr/releases for your first release, but not the most recent one. Can you try to tag each CRAN release and put news items for that version associated with the tag each time you submt to CRAn?  Thanks!

**Comment by leonawicz** [comment]
Thanks! Yeah I will get to this very soon, will be the next thing I do. Sorry I'm a bit sidetracked this time, currently on leave and one of the last things I had done was submit to CRAN and was waiting to make sure everything went through smoothly.

**Comment by leonawicz** [comment]
All done! :)

**Comment by sckott** [comment]
thanks!
