### ISSUE TITLE
Returning multiple subjects (genres)?

### ISSUE THREAD

**Issue by mjockers** [ropensci/epubr#3]
Really great package!  I've been parsing epubs using reticulate and python for too long and then I stumbled upon your fantastic work on this package.  Thank you!  

Now the question: Perhaps I am missing something, but it appears that (by design?) epub_meta() only returns the first "hit" for a tag.  For example, I have an epub with multiple <dc:subject> elements, like this: 
<dc:subject>Legal</dc:subject>
<dc:subject>Mystery</dc:subject>
<dc:subject>Suspense</dc:subject>
but epub_meta() only returns the first one, "Legal".    Is this intentional? Or am I missing a parameter?  

Seems like this could be the result of line 152 in epub.R?  

Thanks for any thoughts.

**Comment by leonawicz** [comment]
Thank you! This is fixed on GitHub now. Will be included in CRAN update soon.
